__author__ = 'sabrsorensen'


def M3UGeneration(name):
    m3u_out = open(name+'.m3u', 'w')
    m3u_out.write("#Playlist " + name + " generated by gmusic_playlist_export\n#EXTM3U\n")

def M3UEntry(path):
    pass